import { createHash, randomUUID } from 'node:crypto';
import { createReadStream } from 'node:fs';
import { realpath, stat } from 'node:fs/promises';
import { isAbsolute, resolve, sep } from 'node:path';
import { assertYouTubeConnected, isYouTubeTrend, youtubeApiData } from './youtube-data-policy.mjs';

const maximumTrendAgeMs = 7 * 24 * 60 * 60 * 1000;
const futureToleranceMs = 5 * 60 * 1000;
const maximumScenes = 12;
const maximumDurationSeconds = 180;

function text(value, name, maximum = 10000) {
  if (typeof value !== 'string' || !value.trim()) throw new Error(`${name} is required`);
  if (value.length > maximum) throw new Error(`${name} is too long (maximum ${maximum})`);
  return value.trim();
}

function optionalText(value, name, maximum = 10000) {
  return value === undefined ? '' : text(value, name, maximum);
}

function description(value) {
  if (typeof value !== 'string' || value.length > 5000) throw new Error('metadata.description must be text of at most 5000 characters');
  return value.trim();
}

function httpUrl(value, name) {
  const result = text(value, name, 4000);
  let parsed;
  try { parsed = new URL(result); } catch { throw new Error(`${name} must be an HTTP(S) URL`); }
  if (!['https:', 'http:'].includes(parsed.protocol) || parsed.username || parsed.password) throw new Error(`${name} must be an HTTP(S) URL without credentials`);
  return parsed.href;
}

function observedTime(value, name = 'observedAt') {
  const input = text(value, name, 100);
  if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(input)) throw new Error(`${name} must be an ISO timestamp with timezone`);
  const [year, month, day] = input.slice(0, 10).split('-').map(Number);
  const calendarDate = new Date(Date.UTC(year, month - 1, day));
  if (calendarDate.getUTCFullYear() !== year || calendarDate.getUTCMonth() + 1 !== month || calendarDate.getUTCDate() !== day) throw new Error(`${name} must be a valid timestamp`);
  const timestamp = Date.parse(input);
  if (!Number.isFinite(timestamp)) throw new Error(`${name} must be a valid timestamp`);
  if (timestamp > Date.now() + futureToleranceMs) throw new Error(`${name} cannot be in the future`);
  return new Date(timestamp).toISOString();
}

function number(value, name, minimum, maximum = Infinity) {
  if (typeof value !== 'number' || !Number.isFinite(value) || value < minimum || value > maximum) throw new Error(`${name} must be between ${minimum} and ${maximum}`);
  return value;
}

function calendarDay(value, name) {
  if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) throw new Error(`${name} must be an ISO calendar date`);
  const [year, month, day] = value.split('-').map(Number);
  const parsed = new Date(Date.UTC(year, month - 1, day));
  if (parsed.getUTCFullYear() !== year || parsed.getUTCMonth() + 1 !== month || parsed.getUTCDate() !== day) throw new Error(`${name} must be a valid calendar date`);
  return value;
}

function rejectClientId(input) {
  if (input?.id !== undefined) throw new Error('Entity IDs are generated by the studio');
}

function requireProject(state, id) {
  const project = state.projects.find((entry) => entry.id === id);
  if (!project) throw new Error(`Project not found: ${id}`);
  if (project.status !== 'active') throw new Error(`Project is not active: ${id}`);
  return project;
}

function requireEpisode(state, id) {
  const episode = state.episodes.find((entry) => entry.id === id);
  if (!episode) throw new Error(`Episode not found: ${id}`);
  return episode;
}

function normalizedTokens(value) {
  return new Set(String(value).normalize('NFKD').replace(/\p{M}/gu, '').toLowerCase().match(/[\p{L}\p{N}]+/gu) ?? []);
}

export function tokenOverlap(left, right) {
  const a = normalizedTokens(left);
  const b = normalizedTokens(right);
  if (!a.size || !b.size) return 0;
  const intersection = [...a].filter((token) => b.has(token)).length;
  return intersection / (a.size + b.size - intersection);
}

function canonicalJson(value) {
  if (Array.isArray(value)) return `[${value.map(canonicalJson).join(',')}]`;
  if (value && typeof value === 'object') return `{${Object.keys(value).sort().filter((key) => value[key] !== undefined).map((key) => `${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(',')}}`;
  return JSON.stringify(value);
}

export function episodeReviewHash(episode) {
  const editorial = {
    title: episode.title, hook: episode.hook, synopsis: episode.synopsis,
    continuityNote: episode.continuityNote, originalAngle: episode.originalAngle,
    factualSources: episode.factualSources ?? [], scenes: episode.scenes,
    metadata: episode.metadata, trendIds: episode.trendIds,
    render: episode.render ? {
      sha256: episode.render.sha256, path: episode.render.path,
      durationSeconds: episode.render.durationSeconds,
      width: episode.render.width, height: episode.render.height,
      framesPerSecond: episode.render.framesPerSecond, format: episode.render.format,
      captionsPath: episode.render.captionsPath, captionsSha256: episode.render.captionsSha256,
      sceneAssets: episode.render.sceneAssets, synthetic: episode.render.synthetic,
    } : null,
  };
  return createHash('sha256').update(canonicalJson(editorial)).digest('hex');
}

export function episodeAssetHash(episode, assets) {
  const ids = [...new Set((episode.render?.sceneAssets ?? []).flatMap((scene) => [scene.visualAssetId, scene.audioAssetId]).filter(Boolean))].sort();
  const manifest = ids.map((id) => {
    const asset = assets.find((entry) => entry.id === id);
    return asset ? { id, episodeId: asset.episodeId, sceneId: asset.sceneId, kind: asset.kind, path: asset.path, sha256: asset.sha256, synthetic: asset.synthetic, provenance: asset.provenance } : { id, missing: true };
  });
  return createHash('sha256').update(canonicalJson(manifest)).digest('hex');
}

export async function studioArtifactPath(directory, relativePath) {
  if (typeof relativePath !== 'string' || isAbsolute(relativePath) || relativePath.includes('\\') || relativePath.split('/').some((part) => part === '..' || part === '.' || !part) || !relativePath.startsWith('assets/')) throw new Error('Artifact path must be relative within assets/');
  const base = resolve(directory);
  const target = resolve(base, relativePath);
  const actualBase = await realpath(base);
  const actualTarget = await realpath(target);
  if (!actualTarget.startsWith(`${actualBase}${sep}assets${sep}`)) throw new Error('Artifact path escapes studio assets directory');
  const info = await stat(actualTarget);
  if (!info.isFile() || info.size < 1) throw new Error('Artifact must be a nonempty regular file');
  return actualTarget;
}

export async function fileSha256(path) {
  const hash = createHash('sha256');
  for await (const chunk of createReadStream(path)) hash.update(chunk);
  return hash.digest('hex');
}

function licenseEvidence(asset) {
  const provenance = asset.provenance;
  if (asset.synthetic !== true) throw new Error(`Asset ${asset.id} must be generated with AI`);
  text(provenance?.provider, `Asset ${asset.id} provider`);
  text(provenance?.model, `Asset ${asset.id} model`);
  text(provenance?.prompt, `Asset ${asset.id} prompt`);
  httpUrl(provenance?.commercialLicense?.url, `Asset ${asset.id} commercialLicense.url`);
  text(provenance?.commercialLicense?.notes ?? provenance?.commercialLicense?.evidence, `Asset ${asset.id} commercialLicense evidence`);
}

async function validateArtifactFile(directory, artifact) {
  if (!/^[a-f0-9]{64}$/i.test(artifact.sha256 ?? '')) throw new Error(`Artifact ${artifact.id ?? 'render'} requires a SHA256`);
  const path = await studioArtifactPath(directory, artifact.path);
  if (await fileSha256(path) !== artifact.sha256.toLowerCase()) throw new Error(`Artifact ${artifact.id ?? 'render'} file hash changed`);
}

async function episodeFindings(state, episode, directory) {
  const findings = [];
  const add = (code, message) => findings.push({ severity: 'blocker', code, message });
  const project = state.projects.find((entry) => entry.id === episode.projectId);
  if (!project || project.status !== 'active') add('project_inactive', 'The linked project must be active.');
  if (project?.mode === 'factual' && !(episode.factualSources?.length > 0)) add('facts_missing', 'Factual content needs claim-specific sources; trend references do not verify facts.');
  try {
    text(episode.title, 'title', 100);
    text(episode.hook, 'hook');
    description(episode.metadata?.description);
    for (const source of episode.factualSources ?? []) { text(source.claim, 'factualSources.claim'); httpUrl(source.url, 'factualSources.url'); }
  } catch (error) { add('editorial_input_invalid', error.message); }
  if (!Array.isArray(episode.scenes) || !episode.scenes.length || episode.scenes.length > maximumScenes) { add('scenes_invalid', 'Episode must retain between 1 and 12 planned scenes.'); return findings; }
  try {
    if (new Set(episode.scenes.map((scene) => scene.id)).size !== episode.scenes.length) throw new Error('Scene IDs must be unique');
    for (const scene of episode.scenes) { text(scene.id, 'scene.id', 100); number(scene.durationSeconds, 'durationSeconds', 1, 60); text(scene.narration, 'narration'); text(scene.visualPrompt, 'visualPrompt'); }
  } catch (error) { add('scene_script_invalid', error.message); }
  const duplicates = state.episodes.filter((other) => other.id !== episode.id && (tokenOverlap(other.title, episode.title) > 0.85 || tokenOverlap((other.scenes ?? []).map((scene) => scene.narration).join(' '), episode.scenes.map((scene) => scene.narration).join(' ')) > 0.85));
  if (duplicates.length) add('duplicate_episode', `Near duplicate episodes: ${duplicates.map((entry) => entry.id).join(', ')}`);
  if (!episode.originalAngle?.trim()) add('original_angle_missing', 'Describe the original narrative angle.');
  if (['rendering', 'publishing', 'processing', 'uploaded', 'scheduled', 'published'].includes(episode.status) || state.publications.some((publication) => publication.episodeId === episode.id && ['reserved', 'uploading', 'sending', 'unknown', 'processing', 'uploaded', 'scheduled', 'published'].includes(publication.status))) add('episode_busy', 'Publication has reserved or frozen this episode; approval cannot change until its outcome is reconciled.');
  if (!episode.render) {
    add('render_missing', 'Generate and watch the final render before approval.');
    return findings;
  }
  if (episode.render.synthetic !== true) add('render_not_synthetic', 'The render must identify the content as AI generated.');
  try { await validateArtifactFile(directory, episode.render); } catch (error) { add('render_invalid', error.message); }
  if (episode.render.captionsPath) {
    try { await validateArtifactFile(directory, { path: episode.render.captionsPath, sha256: episode.render.captionsSha256 }); }
    catch (error) { add('captions_invalid', error.message); }
  }
  const duration = episode.scenes.reduce((sum, scene) => sum + scene.durationSeconds, 0);
  if (!Number.isFinite(episode.render.durationSeconds) || episode.render.durationSeconds <= 0 || episode.render.durationSeconds > maximumDurationSeconds || Math.abs(episode.render.durationSeconds - duration) > 1) add('render_duration', 'Render duration must match the planned scene durations within one second and remain within 180 seconds.');
  const mapping = episode.render.sceneAssets;
  if (!Array.isArray(mapping)) { add('scene_assets_missing', 'Final render requires sceneAssets mappings.'); return findings; }
  const sceneIds = new Set(episode.scenes.map((scene) => scene.id));
  if (mapping.length !== episode.scenes.length || new Set(mapping.map((entry) => entry.sceneId)).size !== mapping.length || mapping.some((entry) => !sceneIds.has(entry.sceneId))) add('scene_mapping_invalid', 'Final render must map each planned scene exactly once.');
  for (const scene of episode.scenes) {
    const linked = mapping.find((entry) => entry.sceneId === scene.id);
    for (const [field, allowed] of [['visualAssetId', ['image', 'video']], ['audioAssetId', ['audio']]]) {
      const asset = state.assets.find((entry) => entry.id === linked?.[field]);
      if (!asset || asset.episodeId !== episode.id || asset.sceneId !== scene.id || !allowed.includes(asset.kind)) { add('scene_asset_invalid', `${scene.id}: ${field} needs a linked AI-generated ${allowed.join('/')} asset.`); continue; }
      try { licenseEvidence(asset); await validateArtifactFile(directory, asset); } catch (error) { add('asset_invalid', error.message); }
    }
  }
  return findings;
}

export class Studio {
  constructor(store, { env = process.env } = {}) { this.store = store; this.youtubeGrantId = env.YTFUN_YOUTUBE_GRANT_ID || 'legacy'; }

  async createProject(input) {
    rejectClientId(input);
    const mode = input.mode ?? 'fiction';
    if (!['fiction', 'factual'].includes(mode)) throw new Error('mode must be fiction or factual');
    const cadence = {
      minHoursBetweenPosts: number(input.cadence?.minHoursBetweenPosts ?? 24, 'minHoursBetweenPosts', 12),
      maxPostsPerRollingDay: number(input.cadence?.maxPostsPerRollingDay ?? 1, 'maxPostsPerRollingDay', 1, 3),
    };
    if (!Number.isInteger(cadence.maxPostsPerRollingDay)) throw new Error('maxPostsPerRollingDay must be an integer');
    const budgetMonthlyUsd = input.budgetMonthlyUsd ?? null;
    if (budgetMonthlyUsd !== null) number(budgetMonthlyUsd, 'budgetMonthlyUsd', 0);
    if (input.costPolicy !== undefined && input.costPolicy !== 'free_first') throw new Error('costPolicy must be free_first');
    const language = text(input.language, 'language', 30);
    if (language.length < 2) throw new Error('language must contain at least 2 characters');
    const project = {
      id: randomUUID(), title: text(input.title, 'title', 160), premise: text(input.premise, 'premise'),
      audience: text(input.audience, 'audience'), language,
      continuity: optionalText(input.continuity, 'continuity'), mode, cadence, budgetMonthlyUsd,
      costPolicy: 'free_first', status: 'active', createdAt: new Date().toISOString(),
    };
    return this.store.transaction((state) => { state.projects.push(project); return project; });
  }

  async listProjects() { return (await this.store.read()).projects; }

  async addTrend(input) {
    rejectClientId(input);
    const trend = { id: randomUUID(), topic: text(input.topic, 'topic', 500), sourceUrl: httpUrl(input.sourceUrl, 'sourceUrl'), observedAt: observedTime(input.observedAt), evidence: text(input.evidence, 'evidence'), ...(input.projectId === undefined ? {} : { projectId: text(input.projectId, 'projectId', 100) }) };
    if (isYouTubeTrend(trend)) trend.apiData = youtubeApiData({ grantId: this.youtubeGrantId, now: Date.parse(trend.observedAt) });
    return this.store.transaction((state) => {
      if (trend.apiData) assertYouTubeConnected(state, { YTFUN_YOUTUBE_GRANT_ID: this.youtubeGrantId });
      if (trend.projectId) requireProject(state, trend.projectId);
      state.trends.push(trend); return trend;
    });
  }

  async planEpisode(input) {
    rejectClientId(input);
    if (!Array.isArray(input.scenes) || !input.scenes.length || input.scenes.length > maximumScenes) throw new Error('scenes must contain between 1 and 12 scenes');
    const scenes = input.scenes.map((scene) => {
      rejectClientId(scene);
      return { id: randomUUID(), durationSeconds: number(scene.durationSeconds, 'durationSeconds', 1, 60), narration: text(scene.narration, 'narration'), visualPrompt: text(scene.visualPrompt, 'visualPrompt') };
    });
    if (scenes.reduce((sum, scene) => sum + scene.durationSeconds, 0) > maximumDurationSeconds) throw new Error('Episode duration cannot exceed 180 seconds');
    const trendIds = input.trendIds ?? [];
    if (!Array.isArray(trendIds) || trendIds.length > 20 || trendIds.some((id) => typeof id !== 'string' || !id) || new Set(trendIds).size !== trendIds.length) throw new Error('trendIds must contain at most 20 unique IDs');
    const factualSources = input.factualSources ?? [];
    if (!Array.isArray(factualSources) || factualSources.length > 40) throw new Error('factualSources must be an array of at most 40 sources');
    const validatedSources = factualSources.map((source) => ({ claim: text(source.claim, 'factualSources.claim'), url: httpUrl(source.url, 'factualSources.url') }));
    const hashtags = input.metadata?.hashtags ?? [];
    if (!Array.isArray(hashtags) || hashtags.length > 8) throw new Error('metadata.hashtags must contain at most 8 relevant hashtags');
    const validatedHashtags = hashtags.map((tag) => {
      const value = text(tag, 'hashtag', 60);
      if (!/^#[\p{L}\p{N}_]+$/u.test(value)) throw new Error('Hashtags must begin with # and contain only letters, numbers or underscores');
      return value;
    });
    if (new Set(validatedHashtags.map((tag) => tag.toLowerCase())).size !== validatedHashtags.length) throw new Error('Hashtags must be unique');
    const episode = {
      id: randomUUID(), projectId: text(input.projectId, 'projectId', 100), title: text(input.title, 'title', 100),
      hook: text(input.hook, 'hook'), synopsis: text(input.synopsis, 'synopsis'),
      continuityNote: optionalText(input.continuityNote, 'continuityNote'), originalAngle: text(input.originalAngle, 'originalAngle'),
      factualSources: validatedSources, scenes,
      metadata: { description: description(input.metadata?.description), hashtags: validatedHashtags },
      trendIds: [...trendIds], createdAt: new Date().toISOString(), status: 'planned', render: null, approval: null, metrics: [],
    };
    return this.store.transaction((state) => {
      const project = requireProject(state, episode.projectId);
      if (project.mode === 'factual' && !validatedSources.length) throw new Error('Factual episodes require claim-specific factualSources; trends do not verify facts');
      for (const id of trendIds) {
        const trend = state.trends.find((entry) => entry.id === id);
        if (!trend) throw new Error(`Trend not found: ${id}`);
        if (trend.projectId && trend.projectId !== episode.projectId) throw new Error(`Trend belongs to another project: ${id}`);
        const observedAt = Date.parse(trend.observedAt);
        if (!Number.isFinite(observedAt) || observedAt > Date.now() + futureToleranceMs || Date.now() - observedAt > maximumTrendAgeMs) throw new Error(`Trend evidence is stale or invalid (maximum age 7 days): ${id}`);
      }
      for (const previous of state.episodes) {
        if (tokenOverlap(previous.title, episode.title) > 0.85 || tokenOverlap(previous.scenes.map((scene) => scene.narration).join(' '), scenes.map((scene) => scene.narration).join(' ')) > 0.85) throw new Error(`Near duplicate episode ${previous.id}: title or narration token overlap exceeds 0.85`);
      }
      state.episodes.push(episode);
      return episode;
    });
  }

  async getEpisode(id) { return requireEpisode(await this.store.read(), id); }

  async recordMetrics(input) {
    rejectClientId(input);
    if (!['youtube', 'facebook', 'tiktok', 'kwai'].includes(input.platform)) throw new Error('platform must be youtube, facebook, tiktok, or kwai');
    const metric = { id: randomUUID(), platform: input.platform, observedAt: observedTime(input.observedAt), sourceUrl: httpUrl(input.sourceUrl, 'sourceUrl') };
    if (metric.platform === 'youtube') metric.apiData = youtubeApiData({ authorized: true, grantId: this.youtubeGrantId, now: Date.parse(metric.observedAt) });
    for (const [key, maximum] of [['views', Infinity], ['retentionRatio', Infinity], ['completionRate', 1], ['revenueUsd', Infinity]]) {
      if (input[key] !== undefined) metric[key] = number(input[key], key, 0, maximum);
    }
    if (metric.views !== undefined && !Number.isInteger(metric.views)) throw new Error('views must be an integer');
    if (!['views', 'retentionRatio', 'completionRate', 'revenueUsd'].some((key) => metric[key] !== undefined)) throw new Error('At least one observed metric is required');
    if ((input.periodStart !== undefined) !== (input.periodEnd !== undefined)) throw new Error('periodStart and periodEnd must be supplied together');
    if (input.periodStart !== undefined) {
      metric.periodStart = calendarDay(input.periodStart, 'periodStart');
      metric.periodEnd = calendarDay(input.periodEnd, 'periodEnd');
      if (metric.periodStart > metric.periodEnd) throw new Error('periodStart must not be after periodEnd');
    }
    return this.store.transaction((state) => {
      if (metric.platform === 'youtube') assertYouTubeConnected(state, { YTFUN_YOUTUBE_GRANT_ID: this.youtubeGrantId });
      const episode = requireEpisode(state, input.episodeId);
      if (episode.metrics.some((entry) => entry.platform === metric.platform && entry.observedAt === metric.observedAt && entry.sourceUrl === metric.sourceUrl && entry.periodStart === metric.periodStart && entry.periodEnd === metric.periodEnd)) throw new Error('Metric observation already recorded');
      episode.metrics.push(metric);
      return metric;
    });
  }

  async editorialReview(id) {
    const state = await this.store.read();
    const episode = requireEpisode(state, id);
    const findings = await episodeFindings(state, episode, this.store.directory);
    return {
      episodeId: episode.id, readyForApproval: findings.length === 0, findings,
      reviewHash: episodeReviewHash(episode),
      limits: { maximumScenes, maximumDurationSeconds, maximumTrendAgeDays: 7, duplicateTokenOverlapThreshold: 0.85, cadenceIsEditorialHypothesis: true, monetization: 'Platform eligibility and revenue require platform decisions and observed results; no views or income are promised.' },
    };
  }

  async approveEpisode(input) {
    const review = {
      originalityChecked: input.review?.originalityChecked, factsChecked: input.review?.factsChecked,
      renderWatched: input.review?.renderWatched, reviewedBy: text(input.review?.reviewedBy, 'review.reviewedBy', 300),
      notes: text(input.review?.notes, 'review.notes'),
    };
    if (review.originalityChecked !== true || review.factsChecked !== true || review.renderWatched !== true) throw new Error('Approval requires originalityChecked, factsChecked and renderWatched attestations');
    return this.store.transaction(async (state) => {
      const episode = requireEpisode(state, input.episodeId);
      const findings = await episodeFindings(state, episode, this.store.directory);
      if (findings.length) throw new Error(`Episode is not ready for approval: ${findings.map((entry) => entry.message).join('; ')}`);
      episode.approval = { reviewHash: episodeReviewHash(episode), assetReviewHash: episodeAssetHash(episode, state.assets), approvedAt: new Date().toISOString(), review };
      episode.status = 'approved';
      return episode;
    });
  }
}
